version: '3.4'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - "mongodb"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80