version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - aspnet-services
    volumes:
      - mongo_data:/data/db

  mongoui:
    image: mongoclient/mongoclient
    container_name: mongoui
    restart: always
    ports:
      - "3000:3000"
    networks:
      - aspnet-services
    depends_on:
     - "catalogdb"

  catalog.api:
   image: ${DOCKER_REGISTRY-}catalogapi
   container_name: catalog.api
   build:
     context: .
     dockerfile: Services/Catalog/Catalog.API/Dockerfile
   ports:
     - "8000:80"
     - "8001:443"
   depends_on:
     - "catalogdb"
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://+:80
     - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
   networks:
     - aspnet-services

networks:
  aspnet-services:
    driver: bridge

volumes:
  mongo_data: