version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - aspnet-services
    volumes:
      - mongo_data:/data/db

  mongoui:
    image: mongoclient/mongoclient
    container_name: mongoui
    restart: always
    ports:
      - "3000:3000"
    networks:
      - aspnet-services
    depends_on:
     - "catalogdb"

  catalog.api:
   image: ${DOCKER_REGISTRY-}catalogapi
   container_name: catalog.api
   build:
     context: .
     dockerfile: Services/Catalog/Catalog.API/Dockerfile
   ports:
     - "8000:80"
     - "8001:443"
   depends_on:
     - "catalogdb"
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://+:80
     - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
   networks:
     - aspnet-services

  basketdb:
    image: redis
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
    networks:
      - aspnet-services

  basket.api:
   image: ${DOCKER_REGISTRY-}basketapi
   container_name: basket.api
   build:
     context: .
     dockerfile: Services/Basket/Basket.Api/Dockerfile
   ports:
     - "8002:80"
     - "8003:443"
   depends_on:
     - "catalogdb"
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://+:80
     - "InMemoryCacheAddress=basketdb:6379"
   networks:
     - aspnet-services

  discountdb:
    image: postgres
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgress_data:/var/lib/postgresql/data/
  discountdbui:
    image: dpage/pgadmin4
    container_name: discountdbui
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
networks:
  aspnet-services:
    driver: bridge

volumes:
  mongo_data:
  postgress_data:
  pgadmin_data: